server:
  port: 8081

spring:
  profiles:
    active: dev

  application:
    name: chat-bot-service

  kafka:
    producer:
      bootstrap-servers:
        - 172.31.18.97:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10

    consumer:
      bootstrap-servers:
        - 172.31.18.97:9092
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: explanet-bot-dev-group

    admin:
      properties:
        bootstrap.servers: 172.31.18.97:9092

  datasource:
    url: jdbc:mysql://172.31.18.97:3306/explanet_dev?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true
    username: alex
    password: dnjscksdn98@
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    jpa:
      repositories:
        bootstrap-mode: default

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create

kafka:
  topics:
    chat-message: chat-message
    guideline-message: guideline-message
    apply-user: apply-user
    approve-user: approve-user
    disapprove-user: disapprove-user
    board-finished: board-finished

  groups:
    guideline-message-group: guideline-message-group
    apply-user-group: apply-user-group
    approve-user-group: approve-user-group
    disapprove-user-group: disapprove-user-group
    board-finished-group: board-finished-group

jwt:
  header: Authorization
  prefix: Bearer
  secret: secretkeytest1234secretkeytest1234secretkeytest1234secretkeytest1234
