server:
  port: 80

ribbon:
  eureka:
    enabled: false

zuul:
  host:
    connect-timeout-millis: 600000
    socket-timeout-millis: 600000
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    chatting-service:
      path: /api/chatting-service/**
      url: http://chatting-service:8080
    chat-bot-service:
      path: /api/chat-bot-service/**
      url: http://chat-bot-service:8081
    base-service:
      path: /api/base-service/**
      url: http://base-service:8082
    board-service:
      path: /api/board-service/**
      url: http://board-service:8083
    login-service:
      path: /api/login-service/**
      url: http://login-service:8084
    mypage-service:
      path: /api/mypage-service/**
      url: http://mypage-service:8085
    watcher-service:
      path: /api/watcher-service/**
      url: http://watcher-service:8086

spring:
  application:
    name: api-gateway

  profiles:
    active: prod

  datasource:
    url: jdbc:mysql://mysql:3306/explanet_prod?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true
    username: explanet
    password: QPVYXdeVWbFP4YK6sLrd
    driver-class-name: com.mysql.cj.jdbc.Driver

    data:
      jpa:
        repositories:
          bootstrap-mode: default

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

jwt:
  header: Authorization
  prefix: Bearer
  secret: DLAAW49Pg59WHI6uEoaLv1OnUlaRvMI-hdh5eYnFIlCfrEhBCnWYfFK0q9nIBf3dqqpwq0GJYiU1bx7xqZWX
