server:
  port: 80

ribbon:
  eureka:
    enabled: false

zuul:
  host:
    connect-timeout-millis: 600000
    socket-timeout-millis: 600000
  sensitiveHeaders: Cookie,Set-Cookie,Authorization
  routes:
    chatting-service:
      path: /api/chatting-service/**
      url: http://localhost:8080
    chat-bot-service:
      path: /api/chat-bot-service/**
      url: http://localhost:8081
    base-service:
      path: /api/base-service/**
      url: http://localhost:8082
    board-service:
      path: /api/board-service/**
      url: http://localhost:8083
    login-service:
      path: /api/login-service/**
      url: http://localhost:8084
    mypage-service:
      path: /api/mypage-service/**
      url: http://localhost:8085
    watcher-service:
      path: /api/watcher-service/**
      url: http://localhost:8086

spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/explanet_local?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true
    username: root
    password: dnjscksdn98@
    driver-class-name: com.mysql.cj.jdbc.Driver

    data:
      jpa:
        repositories:
          bootstrap-mode: default

  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create

  logging:
    level:
      org:
        hibernate:
          stat: debug
          type: trace

jwt:
  header: Authorization
  prefix: Bearer
  secret: secretkeytest1234secretkeytest1234secretkeytest1234secretkeytest1234
