server:
  port: 8081

spring:
  profiles:
    active: dev

  kafka:
    consumer:
      bootstrap-servers:
        - 172.31.18.97:9092
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: explanet-dev-group

  datasource:
    url: jdbc:mysql://172.31.18.97:3306/explanet_dev?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: Dnjscksdn98@
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    jpa:
      repositories:
        bootstrap-mode: default

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
