spring:
  profiles:
    active: default

  devtools:
    restart:
      enabled: true

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb

  data:
    jpa:
      repositories:
        bootstrap-mode: default

  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace
