spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://13.209.141.117:3306/explanet_dev?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

jwt:
  header: Authorization
  prefix: Bearer
  secret: secretkeytest1234secretkeytest1234secretkeytest1234secretkeytest1234
