spring:
  profiles:
    active: prod

  datasource:
    url: jdbc:mysql://mysql:3306/explanet_prod?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true
    username: explanet
    password: QPVYXdeVWbFP4YK6sLrd
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

jwt:
  header: Authorization
  prefix: Bearer
  secret: DLAAW49Pg59WHI6uEoaLv1OnUlaRvMI-hdh5eYnFIlCfrEhBCnWYfFK0q9nIBf3dqqpwq0GJYiU1bx7xqZWX
