spring:
  profiles:
    active: local
---
spring:
  profile: local

  devtools:
    restart:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/ExPlanet-testdb?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    jpa:
      repositories:
        bootstrap-mode: default

  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace
---
spring:
  profile: prod

  datasource:
    url: jdbc:mysql://localhost:3306/ExPlanet?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
