spring:
  profiles:
    active: dev

  application:
    name: base-service

  devtools:
    restart:
      enabled: true

  datasource:
    url: jdbc:mysql://18.215.230.51:3306/explanet_dev?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    jpa:
      repositories:
        bootstrap-mode: default

  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

  logging:
    level:
      org:
        hibernate:
          stat: debug
          type: trace

jwt:
  header: Authorization
  prefix: Bearer
  secret: secretkeytest1234secretkeytest1234secretkeytest1234secretkeytest1234
