server:
  port: 8083

spring:
  profiles:
    active: local

  application:
    name: board-service
    
  kafka:
    producer:
      bootstrap-servers:
        - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10

  datasource:
    url: jdbc:mysql://localhost:3306/explanet_dev?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: dnjscksdn98@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create

jwt:
  header: Authorization
  prefix: Bearer
  secret: secretkeytest1234secretkeytest1234secretkeytest1234secretkeytest1234

kafka:
  topics:
    board-canceled: board-canceled
