spring:
  profiles:
    active: dev

  devtools:
    restart:
      enabled: true

  kafka:
    producer:
      bootstrap-servers:
        - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
    admin:
      properties:
        bootstrap.servers: localhost:9092

  datasource:
    url: jdbc:mysql://localhost:3306/explanet_dev?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: Dnjscksdn98@
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    jpa:
      repositories:
        bootstrap-mode: default

  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace
