server:
  port: 8084

spring:
  profiles:
    active: dev

  application:
    name: login-service

  datasource:
    url: jdbc:mysql://mysql:3306/explanet_dev?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: alex
    password: dnjscksdn98@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create

jwt:
  header: Authorization
  prefix: Bearer
  secret: secretkeytest1234secretkeytest1234secretkeytest1234secretkeytest1234
  expiration: 4
