spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://18.215.230.51:3306/explanet_dev?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

jwt:
  header: Authorization
  prefix: Bearer
  secret: secretkeytest1234secretkeytest1234secretkeytest1234secretkeytest1234
